---
title: "Compile_Sholl_Neurite_Length"
author: "Jeremy Ryan Brown"
date: "`r Sys.Date()`"
output: html_document
---

``` 
This script will prompt users to locate a file in a main directory with 
    subdirectories that represent cell measurements of neurite length and sholl
    complexity from SNT with at least 2 files in each subdirectory including:
      _Sholl_Metrics.csv
      SNT Measurements.csv

The length of each neurite, sum neurite length, num neurites >= 60 microns,
    the sum intersections, the sholl decay value, and R^2 will be compiled
    into 1 tidy dataframe that will be exported and used for graphcrafting.
```

# Libraries

```{r Libraries}
library(tidyverse)
library(ggplot2)
library(DescTools)
library(stringr)

Sys.setlocale(locale="C")
```

# Global variables

```{r Global variables}
{
# Not doing a great job of delineating global and local variables as of now.
}
```


# Functions

```{r Functions}

match_col_classes <- function(df1, df2) {

  shared_col_names <- names(df1)[names(df1) %in% names(df2)]
  shared_col_types <- sapply(df1[,shared_col_names], class)

  for (n in shared_col_names) {
     class(df2[, n]) <- shared_col_types[n]
  }

  return(df2)
 }

tidy_sholl_data <- function(raw_data)
{
  return(raw_data |>
        select("Sholl decay", "Sum inters. (sampled)", "R^2"))
}

tidy_SNT_data <- function(raw_data)
{
  return(raw_data |> 
           select(starts_with("Path length"), starts_with("SWC"), starts_with("No.")))
}

compile_tidy_data <- function(tidy_sholl_data, tidy_SNT_data)
{
  return(bind_cols(tidy_sholl_data, tidy_SNT_data))
}

add_labels_to_tidy_data <- function(tidy_data,
                                    date_=NULL,
                                    cell_=NULL, 
                                    condition_=NULL, 
                                    timepoint_=NULL)
{
  labeled_data <- tidy_data |>
    mutate(date=c(date_)) |>
    mutate(cell=c(cell_))|>
    mutate(condition=c(condition_)) |>
    mutate(timepoint= c(timepoint_))
  
  return(labeled_data)
}

iterate_on_files_in_directory <- function(sholl_files_in_dir=NULL,
                                          SNT_files_in_dir=NULL)
{
  # Check for a null value for sholl files meaning no files were passed to us.
  if(is.null(sholl_files_in_dir))
  {
    print("No SHOLL CSVs passed to the interate_on_files_in_directory function. 
          Choose a directory with the correct CSV files present. 
          The script will now exit.")
    return()
  }
  
  # Check for a null value for SNT files meaning no files were passed to us.
  if(is.null(SNT_files_in_dir))
  {
    print("No SNT CSVs passed to the interate_on_files_in_directory function. 
          Choose a directory with the correct CSV files present. 
          The script will now exit.")
    return()
  }
  
  tidy_dfs <- list()
  
  # Begin iterating on the files in the directory
  for(i in 1:length(sholl_files_in_dir))
  {
    filepath_to_sholl_csv <- sholl_files_in_dir[i]
    filepath_to_SNT_csv <- SNT_files_in_dir[i]
    
    raw_sholl_data <- read.csv(filepath_to_sholl_csv, check.names=F)
    raw_SNT_data <- read.csv(filepath_to_SNT_csv, check.names=F)
    
    sholl_tidy <- tidy_sholl_data(raw_sholl_data)
    SNT_tidy <- tidy_SNT_data(raw_SNT_data)
    
    compiled_tidy <- compile_tidy_data(raw_sholl_data, raw_SNT_data)

    # Parse the identifying variables from the filepath
    identifiers_start = str_locate(filepath_to_sholl_csv, "/plated")[1]
    identifiers_substring = substring(filepath_to_sholl_csv, 
                                             identifiers_start, 
                                             str_length(filepath_to_sholl_csv))
    
    date_end = str_locate_all(identifiers_substring, "/")[[1]][2]
    date_substring = substring(identifiers_substring, 
                                2, 
                                date_end-1)
    
    condition_end = str_locate_all(identifiers_substring, "/")[[1]][3]
    condition_substring = substring(identifiers_substring,
                                    date_end+1,
                                    condition_end-1)
    
    cell_start = str_locate_all(identifiers_substring, "/")[[1]][4]
    cell_end = str_locate_all(identifiers_substring, "/")[[1]][5]
    cell_substring = substring(identifiers_substring,
                               cell_start+1,
                               cell_end-1)
    
    if(str_detect(dirpath,"DIV1"))
    {
      timepoint = "1"
    }else
    {
      timepoint="error"
    }
    # Add the identifying variables to the dataframe and append to main list
    data_to_append <- add_labels_to_tidy_data(compiled_tidy,
                                date_=date_substring,
                                cell_=cell_substring,
                                condition_=condition_substring,
                                timepoint_=timepoint
                                )
    tidy_dfs[[i]] <- data_to_append
    
  }
  # Now outside of iteration loop return the main list
  return(tidy_dfs)
}

```

# Data import and tidying

```{r Data import and tidying}

# Import the data by looping through Sholl_Metrics.csv files in a directory
# prompt the user to choose a directory with subdirectory containing the csvs
# then we will iterate through each Sholl_Metrics and SNT_Measurements
dirpath_raw = file.choose()
dirpath_intermediate = SplitPath(dirpath_raw)$fullpath
dirpath_end = str_locate(dirpath_intermediate, "/SNT_Analysis/")[1]+13
dirpath = substring(dirpath_intermediate, 0, dirpath_end)

sholl_files_in_dir = list.files(path=dirpath,
           pattern='^\\s*[Sholl_Metrics]+s*[csv]',
           all.files=F,
           full.names=T,
           recursive=T)

SNT_files_in_dir = list.files(path=dirpath,
           pattern='^\\s*[SNT Measurements]+s*[csv]',
           all.files=F,
           full.names=T,
           recursive=T)

compiled_labeled_tidy <- iterate_on_files_in_directory(sholl_files_in_dir, 
                                                       SNT_files_in_dir)

df_to_export <- compiled_labeled_tidy[[1]]

for(i in 2:length(sholl_files_in_dir))# compile list of dataframes into 1 df
{
  df_to_append <- match_col_classes(compiled_labeled_tidy[[1]], 
                                    compiled_labeled_tidy[[i]])
  df_to_export <- bind_rows(df_to_export, df_to_append)
}

#tidy so that all we see is SNT data for now
df_to_export <- df_to_export |>
  select(starts_with('Path length'), 
         ends_with('(5m)'), 
         date, 
         cell, 
         condition, 
         timepoint)

save_path = paste(dirpath,
            "from_R_.csv",
            sep="")
```

# Data saving
```{r Data saving}

write.csv(df_to_export, save_path)

```
