---
title: "Compile_Sholl_Neurite_Length"
author: "Jeremy Ryan Brown"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

``` 
Instructions found in README.md
```

# Libraries

```{r Libraries}
library(tidyverse)
library(DescTools)
library(stringr)

Sys.setlocale(locale="C")
```

# Functions

```{r Functions}

#This function will take in the messy data from SNT and tidy it as well as 
# perform calculations using dplyr.
tidy_SNT_data <- function(raw_data)
{
  return(raw_data |> 
           mutate(path_length_microns = as.numeric(`Path.length...m.`)) |> 
           select(path_length_microns) |>
           filter_out(path_length_microns == 0) |>
           na.omit() |>
           distinct() |>
           arrange(desc(path_length_microns), .by_group=TRUE) |>
           mutate(neurite_number  = seq(1, n())) |>
           mutate(path_length_sum = sum(path_length_microns, na.rm=TRUE)) |>
           mutate(neurite_per_sum = path_length_microns/path_length_sum) |>
           mutate(morphological_long_axon_present = if_any(everything(), 
                                                      ~ round(
                                                        path_length_microns) >= 
                                                        60)) |>
           mutate(morphological_short_axon_present = if_any(everything(), 
                                                      ~ round(
                                                        path_length_microns) >= 
                                                        40)))
}
# This function will add a series of predefined but variable labels to tidy dfs
add_labels_to_dataframe <- function(tidy_data,
                                    date_=NULL,
                                    cell_=NULL, 
                                    condition_=NULL, 
                                    timepoint_=NULL)
{
  labeled_data <- tidy_data |>
    mutate(date=c(date_)) |>
    mutate(cell=c(cell_))|>
    mutate(condition=c(condition_)) |>
    mutate(timepoint= c(timepoint_))
  
  return(labeled_data)
}
# This function will strip the identifiers from the path to each csv file
parse_path_to_identifiers <- function(path_to_parse=NULL)
{
  if(is.null(path_to_parse)){return(NULL)} # escape if no path was passed 
  # Parse the identifying variables from the filepath
    identifiers_start = str_locate(path_to_parse, "/plated")[1]
    identifiers_substring_ = substring(path_to_parse, 
                                             identifiers_start, 
                                             str_length(path_to_parse))
    
    date_end = str_locate_all(identifiers_substring_, "/")[[1]][2]
    date_substring_ = substring(identifiers_substring_, 
                                2, 
                                date_end-1)
    
    condition_end = str_locate_all(identifiers_substring_, "/")[[1]][3]
    condition_substring_ = substring(identifiers_substring_,
                                    date_end+1,
                                    condition_end-1)
    
    cell_start = str_locate_all(identifiers_substring_, "/")[[1]][4]
    cell_end = str_locate_all(identifiers_substring_, "/")[[1]][5]
    cell_substring_ = substring(identifiers_substring_,
                               cell_start+1,
                               cell_end-1)
    
    # Define the timepoint string as error before fixing it if we find the DIV
    #   this results in the default if no DIV string is found as "ERROR"
    timepoint_="ERROR"
    
    if(str_detect(path_to_parse,"DIV1"))
    {
      timepoint_ = "1"
    }
    
    if(str_detect(path_to_parse,"DIV2"))
    {
      timepoint_="2"
    }
    
    if(str_detect(path_to_parse,"DIV3"))
    {
      timepoint_="3"
    }
    
    return(c(date_substring_,
             condition_substring_,
             cell_substring_,
             timepoint_))
}
#This is essentially the main loop of the script that will read, parse, and 
# compile SNT Measurements.csv files
iterate_on_files_in_directory <- function()
{
  
  # Check for a null value for SNT files meaning no files were passed to us.
  if(is.null(SNT_files_in_dir))
  {
    print("No SNT CSVs passed to the interate_on_files_in_directory function. 
          Choose a directory with the correct CSV files present. 
          The script will now exit.")
    return()
  }
  
  # Create a list of dataframes to store our dataframes in
  tidy_dfs <- list()
  
  # Begin iterating on the files in the directory
  for(i in 1:length(SNT_files_in_dir))
  {
    filepath_to_SNT_csv <- SNT_files_in_dir[i]
    raw_SNT_data <- read.csv(filepath_to_SNT_csv)
    # We will make use of the user-defined functions to simplify this area
    # Strip and store the identifiers locally
    identifiers_ <- parse_path_to_identifiers(filepath_to_SNT_csv)
    # Tidy and add calculations to the dataframe
    SNT_tidy <- tidy_SNT_data(raw_SNT_data)
    # Add the identifying variables to the dataframe and 
    labeled_tidy <- add_labels_to_dataframe(SNT_tidy,
                                                     date_=identifiers_[1],
                                                     cell_=identifiers_[3],
                                                     condition_=identifiers_[2],
                                                     timepoint_=identifiers_[4])
    # Append new dataframe to main list of dataframes that we will return
    tidy_dfs[[i]] <- labeled_tidy
  }
  # Now outside of the main iteration loop return the main list of dataframes
  return(tidy_dfs)
}

find_and_concatenate_compiled_csvs <- function()
{
  compiled_files_in_dir = list.files(path=dirpath_to_main_dir,
           pattern='R_compiled.csv',
           all.files=F,
           full.names=T,
           recursive=T)
  
  concatenated_compiled_df <- read.csv(compiled_files_in_dir[1])
  
  for(i in 1:length(compiled_files_in_dir))
  {
    compiled_file <- read.csv(compiled_files_in_dir[i])
    concatenated_compiled_df <- bind_rows(concatenated_compiled_df, 
                                          compiled_file)
  }
  return(concatenated_compiled_df)
}

```

# Data import and tidying

```{r Data import and tidying}

# Import the data by looping through SNT Measurements.csv files in a directory.
dirpath_raw = file.choose()
dirpath_intermediate = SplitPath(dirpath_raw)$fullpath
dirpath_end = str_locate(dirpath_intermediate, 
                         regex('/SNT_analysis/', 
                               ignore_case=TRUE))[1]+13
dirpath = substring(dirpath_intermediate, 0, dirpath_end)

SNT_files_in_dir = list.files(path=dirpath,
           pattern='^\\s*[SNT Measurements]+s*[csv]',
           all.files=F,
           full.names=T,
           recursive=T)

test_raw_df <- read.csv(SNT_files_in_dir[2])

identifiers <- parse_path_to_identifiers(SNT_files_in_dir[1])

compiled_labeled_tidys <- iterate_on_files_in_directory()

df_to_export <- compiled_labeled_tidys[[1]]

for(i in 2:length(compiled_labeled_tidys))# compile list of dataframes into 1 df
{
  df_to_export <- bind_rows(df_to_export, compiled_labeled_tidys[[i]])
}

#Arrange the compiled data by path length within groups defined by cell ID
df_to_export <- df_to_export |>
  group_by(cell) |>
  arrange(desc(path_length_microns), .by_group=TRUE)
#Create a string path to save the compiled csv data
save_path_compiled_csv = str_c(dirpath,
                  identifiers[1],
                  "_",
                  identifiers[2],
                  "_DIV",
                  identifiers[4],
                  "_",
                  "R_compiled.csv")
#Store the summaries created from the grouped compiled data
summary_to_export <- df_to_export |>
  summary() |>
  tibble() |>
  add_labels_to_dataframe(date_=identifiers[1],
                          cell_="NA",
                          condition_=identifiers[2],
                          timepoint_=identifiers[4])
#Create a string path to save the summaries of the compiled data
save_path_csv_summary = str_c(dirpath,
                  identifiers[1],
                  "_",
                  identifiers[2],
                  "_DIV",
                  identifiers[4],
                  "_",
                  "R_summary.csv")
```

# Data saving
```{r Data saving}
# Print and save the compiled dataframe
# print(df_to_export)
write.csv(df_to_export, save_path_compiled_csv)
#Print and save the summaries of the data in the compiled dataframe
print(summary_to_export)
write.csv(summary_to_export, save_path_csv_summary)
```
# Compile and save all compiled dataframes for graphing
```{r Compile all complations formatted to graph and then save}

full_compiled_csv <- find_and_concatenate_compiled_csvs()

dirpath_to_main_dir_end <- str_locate(dirpath, "/data")[1]+5
dirpath_to_main_dir <- substring(dirpath, 
                                    0, 
                                    dirpath_to_main_dir_end)

save_path_full_compiled_csv <- str_c(dirpath_to_main_dir,
                  "DIV",
                  identifiers[4],
                  "_",
                  "R_compiled_to_graph.csv")

write.csv(full_compiled_csv, save_path_full_compiled_csv)
```